/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cmm.jft_ui.configuration;

import com.cmm.jft_ui.forms.AbstractForm;
import com.cmm.jft_ui.forms.Forms;

/**
 *
 * @author Cristiano M Martins
 */
public class DBInitializationForm extends AbstractForm {

    /**
     * Creates new form DBInitializationForm
     */
    public DBInitializationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        chkCountries = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        chkCurrencies = new javax.swing.JCheckBox();
        chkAccounts = new javax.swing.JCheckBox();
        chkExchanges = new javax.swing.JCheckBox();
        chkCompanies = new javax.swing.JCheckBox();
        chkMarketCodes = new javax.swing.JCheckBox();
        chkSecTypes = new javax.swing.JCheckBox();
        chkISIN = new javax.swing.JCheckBox();
        chkSecurities = new javax.swing.JCheckBox();
        chkDateCodes = new javax.swing.JCheckBox();
        chkHistQuotes = new javax.swing.JCheckBox();
        chkEarnings = new javax.swing.JCheckBox();
        chkTickData = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DB Initialization");
        setResizable(false);

        btnCancel.setText("Cancel");

        btnOK.setText("OK");

        btnStart.setText("Start");

        chkCountries.setText("Countries");

        jLabel1.setText("Initialize Data:");

        chkCurrencies.setText("Currencies");

        chkAccounts.setText("Accounts");

        chkExchanges.setText("Exchanges");

        chkCompanies.setText("Companies");

        chkMarketCodes.setText("Market Codes");

        chkSecTypes.setText("Security Types");

        chkISIN.setText("Isin");

        chkSecurities.setText("Securities");

        chkDateCodes.setText("Date Codes");

        chkHistQuotes.setText("Historical Quotes");

        chkEarnings.setText("Earnings");

        chkTickData.setText("Tick Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart)
                            .addComponent(jLabel1)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCountries)
                                    .addComponent(chkCurrencies)
                                    .addComponent(chkAccounts)
                                    .addComponent(chkMarketCodes)
                                    .addComponent(chkCompanies)
                                    .addComponent(chkExchanges)
                                    .addComponent(chkISIN))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(chkHistQuotes)
                                        .addComponent(chkDateCodes, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkEarnings, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkTickData, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(chkSecurities)
                                    .addComponent(chkSecTypes))))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCountries)
                    .addComponent(chkSecTypes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCurrencies)
                    .addComponent(chkSecurities))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAccounts)
                    .addComponent(chkDateCodes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkExchanges)
                    .addComponent(chkHistQuotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCompanies)
                    .addComponent(chkEarnings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkISIN)
                    .addComponent(chkTickData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMarketCodes)
                .addGap(17, 17, 17)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBInitializationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBInitializationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBInitializationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBInitializationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBInitializationForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnStart;
    private javax.swing.JCheckBox chkAccounts;
    private javax.swing.JCheckBox chkCompanies;
    private javax.swing.JCheckBox chkCountries;
    private javax.swing.JCheckBox chkCurrencies;
    private javax.swing.JCheckBox chkDateCodes;
    private javax.swing.JCheckBox chkEarnings;
    private javax.swing.JCheckBox chkExchanges;
    private javax.swing.JCheckBox chkHistQuotes;
    private javax.swing.JCheckBox chkISIN;
    private javax.swing.JCheckBox chkMarketCodes;
    private javax.swing.JCheckBox chkSecTypes;
    private javax.swing.JCheckBox chkSecurities;
    private javax.swing.JCheckBox chkTickData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
    /* (non-Javadoc)
     * @see com.cmm.jft_ui.Forms#setData(java.lang.Object)
     */
    @Override
    public void setData(Object data) {
	// TODO Auto-generated method stub
	
    }

    /* (non-Javadoc)
     * @see com.cmm.jft_ui.Forms#addListeners()
     */
    @Override
    public void addListeners() {
	// TODO Auto-generated method stub
	
    }

    /* (non-Javadoc)
     * @see com.cmm.jft_ui.Forms#loadData()
     */
    @Override
    public void loadData() {
	// TODO Auto-generated method stub
	
    }
    
}
