
package com.cmm.jft.ui.forms;

import com.cmm.jft.ui.forms.trading.BookForm;
import javax.swing.UIManager;

import com.cmm.jft.ui.forms.trading.DOMForm;
import com.cmm.jft.ui.forms.trading.NewsForm;


/**
 *
 * @author Cristiano M Martins
 */
public class ProgramForm extends AbstractForm {

    /** Creates new form Program */
    public ProgramForm() {
        setLookAndFeel();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDom = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnTT = new javax.swing.JButton();
        btnPos = new javax.swing.JButton();
        btnTool = new javax.swing.JButton();
        btnNews = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDom.setText("DOM");
        btnDom.setFocusable(false);
        btnDom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDomActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDom);

        btnBook.setText("Book");
        btnBook.setFocusable(false);
        btnBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBook);

        btnTT.setText("T&T");
        btnTT.setFocusable(false);
        btnTT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTT);

        btnPos.setText("Posição");
        btnPos.setFocusable(false);
        btnPos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPos);

        btnTool.setText("Ferramentas");
        btnTool.setFocusable(false);
        btnTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTool);

        btnNews.setText("Notícias");
        btnNews.setFocusable(false);
        btnNews.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNews.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNews);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDomActionPerformed
    java.awt
        .EventQueue
        .invokeLater(new Runnable() {
            public void run() {
                new DOMForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnDomActionPerformed

    private void btnNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewsActionPerformed
        java.awt
        .EventQueue
        .invokeLater(new Runnable() {
            public void run() {
                new NewsForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnNewsActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        java.awt
        .EventQueue
        .invokeLater(new Runnable() {
            public void run() {
                new BookForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTTActionPerformed

    private void btnPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPosActionPerformed

    private void btnToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        setLookAndFeel();
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new ProgramForm().setVisible(true);
                }
            });
    }
    
    private static void setLookAndFeel(){
        try {
               javax.swing
                         .UIManager
                         .setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ProgramForm.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ProgramForm.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ProgramForm.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(ProgramForm.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDom;
    private javax.swing.JButton btnNews;
    private javax.swing.JButton btnPos;
    private javax.swing.JButton btnTT;
    private javax.swing.JButton btnTool;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
