/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cmm.jft_ui.trading;

import com.cmm.jft.core.enums.GeneralStatus;
import com.cmm.jft.db.DBFacade;
import com.cmm.jft.db.DBObject;
import com.cmm.jft.db.exceptions.DataBaseException;
import com.cmm.jft.trading.Orders;
import com.cmm.jft.trading.Position;
import com.cmm.jft.trading.enums.TradeTypes;
import com.cmm.jft.trading.services.TradingService;

import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;

import com.cmm.jft_ui.ObjectForms;
import com.cmm.jft_ui.forms.AbstractForm;
import com.cmm.jft_ui.forms.Events;
import com.cmm.jft_ui.forms.FormStates;
import com.cmm.jft_ui.forms.FormsFactory;
import com.cmm.jft_ui.forms.binding.FormBinder;
import com.cmm.jft_ui.utils.FormUtils;
import com.cmm.jft_ui.utils.GenericTableModel;

/**
 *
 * @author Cristiano M Martins
 */
public class TradeForm extends AbstractForm  {

    /**
     * Creates new form TradeForm
     */
    public TradeForm() {
	initComponents();
	
	binder = new FormBinder();
	binder.register("tradeID", lblSerial);
	binder.register("tradeSerial", txtSerial);
	binder.register("entryID.entryID", txtEntryID);
	binder.register("symbol", sbSecurity);
	binder.register("openDate", dtOpenDate);
	binder.register("closeDate", dtCloseDate);
	binder.register("tradeStatus", cmbTradeStatus);
	binder.register("tradeType", cmbTradeType);
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dtOpenDate = new com.toedter.calendar.JDateChooser();
        txtSerial = new javax.swing.JTextField();
        cmbTradeType = new javax.swing.JComboBox();
        cmbTradeStatus = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEntryID = new javax.swing.JTextField();
        dtCloseDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        sbSecurity = new com.cmm.searchbox.SearchBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("TradeID");

        lblSerial.setText("0");

        btnCancel.setText("Cancel");

        btnOK.setText("OK");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--plus.png"))); // NOI18N

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--pencil.png"))); // NOI18N

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--minus.png"))); // NOI18N

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tblOrders);

        jLabel2.setText("Serial");

        jLabel3.setText("EntryID");

        jLabel4.setText("Orders");

        jLabel5.setText("Security");

        jLabel6.setText("Open Date");

        cmbTradeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTradeStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Trade Type");

        jLabel8.setText("Trade Status");

        jLabel9.setText("Close Date");

        sbSecurity.setQuery("select securityid, symbol from stock \nunion \nselect securityid, symbol from stockoption");
        sbSecurity.setResultField("Symbol");
        sbSecurity.setSearchField("Symbol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSerial)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dtCloseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txtEntryID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txtSerial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtOpenDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbTradeType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbTradeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sbSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSerial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sbSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbTradeType, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 309, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEntryID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dtOpenDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(dtCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbTradeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRemove))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnOK))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cmbTradeStatus;
    private javax.swing.JComboBox cmbTradeType;
    private com.toedter.calendar.JDateChooser dtCloseDate;
    private com.toedter.calendar.JDateChooser dtOpenDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblSerial;
    private com.cmm.searchbox.SearchBox sbSecurity;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtEntryID;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables



    /* (non-Javadoc)
     * @see com.cmm.jft_ui.forms.AbstractForm#addListeners()
     */
    @Override
    public void addListeners() {
	super.addListeners();
	btnAdd.addActionListener(new GerEvents(this));
	btnEdit.addActionListener(new GerEvents(this));
	btnRemove.addActionListener(new GerEvents(this));
	this.addWindowListener(new GerEvents(this));
    }

    /* (non-Javadoc)
     * @see com.cmm.jft_ui.forms.AbstractForm#loadData()
     */
    @Override
    public void loadData() {
	
	sbSecurity.setConnection(DBFacade.getInstance().getConnection());
	sbSecurity.setFields(new String[]{"SecurityID", "Symbol"});
	sbSecurity.setResultField("Symbol");
	sbSecurity.setSearchField("Symbol");
	sbSecurity.setQuery("select securityid, symbol from stock \nunion \nselect securityid, symbol from stockoption order by securityid, symbol");

	FormUtils.getInstance().addItensToCombo(cmbTradeStatus, GeneralStatus.values());
	FormUtils.getInstance().addItensToCombo(cmbTradeType, TradeTypes.values());

	GenericTableModel<Orders> model = new GenericTableModel<Orders>(Orders.class);
	
	model.showColumnWithAlias("securityID", "Security");
        model.showColumnWithAlias("side", "Side");
        model.showColumnWithAlias("volume", "Volume");
        model.showColumnWithAlias("price", "Price");
        model.showColumnWithAlias("orderStatus", "Order Status");
        
        model.rebuildColumns();
        if(data!=null) {
            
        	//model.setValues(((Trade)data).getOrdersList());
        }
        
        switch(state) {
        case ADD:
            //data = new Trade();
            btnAdd.setEnabled(false);
            btnEdit.setEnabled(false);
            btnRemove.setEnabled(false);
            break;
        case CANCELED:
            btnAdd.setEnabled(false);	
            btnEdit.setEnabled(false);
            btnRemove.setEnabled(false);
            break;
        case CLOSED:
            btnAdd.setEnabled(false);	
            btnEdit.setEnabled(false);
            btnRemove.setEnabled(false);
            break;
        case OK:
            btnAdd.setEnabled(true);	
            btnEdit.setEnabled(true);
            btnRemove.setEnabled(true);
            break;
        case OPEN:
            btnAdd.setEnabled(true);	
            btnEdit.setEnabled(true);
            btnRemove.setEnabled(true);
            break;
        }
        
	tblOrders.setModel(model);
	super.loadData();
	
    }


    private class GerEvents extends Events{

	/**
	 * @param frame
	 */
	public GerEvents(AbstractForm frame) {
	    super(frame);
	}


	/* (non-Javadoc)
	 * @see com.cmm.jft_ui.forms.Events#actionPerformed(java.awt.event.ActionEvent)
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
	    //super.actionPerformed(e);
	    if(e.getSource() == btnAdd) {
//		Position p = (Position) data;
//		FormUtils.getInstance().clearParameters();
//		FormUtils.getInstance().addParameter("TradeType", p..getTradeType());
//		FormUtils.getInstance().addParameter("Symbol", t.getSymbol());
		
		FormsFactory.openForm(ObjectForms.ORDER, FormStates.ADD);
	    }else if(e.getSource() == btnEdit) {
		FormsFactory.openFormBySelectedObject(tblOrders, ObjectForms.ORDER, FormStates.UPDATE);
	    }else if(e.getSource() == btnRemove) {
		FormsFactory.openFormBySelectedObject(tblOrders, ObjectForms.ORDER, FormStates.CANCELED);
	    }
	}
	
	/* (non-Javadoc)
	 * @see com.cmm.jft_ui.forms.Events#windowActivated(java.awt.event.WindowEvent)
	 */
	@Override
	public void windowActivated(WindowEvent e) {
//	    try {
//		data = (DBObject) DBFacade.getInstance()._findByKey(Trade.class, ((Trade)data).getTradeID());
//		((GenericTableModel<Orders>)tblOrders.getModel()).setValues(((Trade)data).getOrdersList());
//	    } catch (DataBaseException ex) {
//		ex.printStackTrace();
//	    }
	    
	}

    }



}