/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cmm.jft_ui.trading;

import com.cmm.jft.db.DBFacade;
import com.cmm.jft.db.exceptions.DataBaseException;
import com.cmm.jft.trading.Position;

import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;

import org.apache.log4j.Level;

import com.cmm.jft_ui.ObjectForms;
import com.cmm.jft_ui.forms.AbstractForm;
import com.cmm.jft_ui.forms.Events;
import com.cmm.jft_ui.forms.FormStates;
import com.cmm.jft_ui.forms.FormsFactory;
import com.cmm.jft_ui.utils.GenericTableModel;
import com.cmm.logging.Logging;

/**
 *
 * @author Cristiano M Martins
 */
public class TradeManagerForm extends AbstractForm {

    /**
     * Creates new form TradeManagerForm
     */
    public TradeManagerForm() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jScrollPaneTrades = new javax.swing.JScrollPane();
	tblTrades = new javax.swing.JTable();
	jLabel1 = new javax.swing.JLabel();
	txtPosition = new javax.swing.JTextField();
	jToolBar = new javax.swing.JToolBar();
	btnAddTrade = new javax.swing.JButton();
	btnEditTrade = new javax.swing.JButton();
	btnCancelTrade = new javax.swing.JButton();

	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	tblTrades.setModel(new javax.swing.table.DefaultTableModel(
		new Object [][] {
			{null, null, null, null},
			{null, null, null, null},
			{null, null, null, null},
			{null, null, null, null}
		},
		new String [] {
			"Title 1", "Title 2", "Title 3", "Title 4"
		}
		));
	jScrollPaneTrades.setViewportView(tblTrades);

	jLabel1.setText("Position");

	txtPosition.setEnabled(false);

	jToolBar.setFloatable(false);
	jToolBar.setRollover(true);

	btnAddTrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--plus.png"))); // NOI18N
	btnAddTrade.setFocusable(false);
	btnAddTrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	btnAddTrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
	jToolBar.add(btnAddTrade);

	btnEditTrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--pencil.png"))); // NOI18N
	btnEditTrade.setFocusable(false);
	btnEditTrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	btnEditTrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
	jToolBar.add(btnEditTrade);

	btnCancelTrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons/ticket--minus.png"))); // NOI18N
	btnCancelTrade.setFocusable(false);
	btnCancelTrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	btnCancelTrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
	jToolBar.add(btnCancelTrade);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
			.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			.addComponent(jLabel1)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
			.addContainerGap())
			.addComponent(jScrollPaneTrades)
		);
	layout.setVerticalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
			.addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
			.addGap(19, 19, 19)
			.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel1)
				.addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
				.addComponent(jScrollPaneTrades, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

	pack();
    }// </editor-fold>//GEN-END:initComponents



    /* (non-Javadoc)
     * @see com.cmm.jft_ui.forms.AbstractForm#addListeners()
     */
    @Override
    public void addListeners() {
	btnAddTrade.addActionListener(new GerEvents(this));
	btnCancelTrade.addActionListener(new GerEvents(this));
	btnEditTrade.addActionListener(new GerEvents(this));
	this.addWindowListener(new GerEvents(this));
    }

    /* (non-Javadoc)
     * @see com.cmm.jft_ui.forms.AbstractForm#loadData()
     */
    @Override
    public void loadData() {

	GenericTableModel<Position> mTrade = new GenericTableModel<Position>(Position.class);

	mTrade.showColumnWithAlias("symbol", "Symbol");
	mTrade.showColumnWithAlias("tradeSerial", "Trade Serial");
	mTrade.showColumnWithAlias("tradeStatus", "Trade Status");
	mTrade.showColumnWithAlias("tradeType", "Trade Type");

	mTrade.rebuildColumns();

	try {
	    DBFacade.getInstance().closeSession();
	    mTrade.setValues(DBFacade.getInstance()._listResults("Trade.findAll", null));
	} catch (DataBaseException e) {
	    Logging.getInstance().log(getClass(), e, Level.ERROR);	    
	}

	tblTrades.setModel(mTrade);

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrade;
    private javax.swing.JButton btnCancelTrade;
    private javax.swing.JButton btnEditTrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneTrades;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JTable tblTrades;
    private javax.swing.JTextField txtPosition;
    // End of variables declaration//GEN-END:variables


    private class GerEvents extends Events{

	/**
	 * @param frame
	 */
	public GerEvents(AbstractForm frame) {
	    super(frame);
	}

	/* (non-Javadoc)
	 * @see com.cmm.jft_ui.forms.Events#actionPerformed(java.awt.event.ActionEvent)
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
	    if(e.getSource() == btnAddTrade) {
		FormsFactory.openForm(ObjectForms.TRADE, FormStates.ADD);
	    }
	    else if(e.getSource() == btnCancelTrade) {
		FormsFactory.openFormBySelectedObject(tblTrades, ObjectForms.TRADE, FormStates.UPDATE);
	    }
	    else if(e.getSource() == btnEditTrade) {
		FormsFactory.openFormBySelectedObject(tblTrades, ObjectForms.TRADE, FormStates.UPDATE);
	    }

	}

	/* (non-Javadoc)
	 * @see com.cmm.jft_ui.forms.Events#windowActivated(java.awt.event.WindowEvent)
	 */
	@Override
	public void windowActivated(WindowEvent e) {
	    try {
		DBFacade.getInstance().closeSession();
		//((GenericTableModel<Position>)tblTrades.getModel()).setValues(DBFacade.getInstance()._listResults("Trade.findAll", null));
	    } catch (DataBaseException ex) {
		Logging.getInstance().log(getClass(), ex, Level.ERROR);	    
	    }
	}

    }

}
