/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cmm.searchbox;

import com.cmm.searchbox.core.SearchUtil;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Cristiano M Martins
 */
public class Grid extends javax.swing.JFrame {

    /**
     * Creates new form Grid
     */
    public Grid(SearchUtil searchUtil) {
        initComponents();
        addListeners();
        this.sUtil = searchUtil;
    }

    private void addListeners(){
        btnCancel.addActionListener(new GerEvents(this));
        btnOK.addActionListener(new GerEvents(this));
        btnSearch.addActionListener(new GerEvents(this));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneResult = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblLabel = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.UTILITY);

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.setFillsViewportHeight(true);
        jScrollPaneResult.setViewportView(tblResult);

        btnCancel.setText("Cancel");

        btnOK.setText("OK");

        lblLabel.setText("jLabel1");

        btnSearch.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
            .addComponent(jScrollPaneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPaneResult;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    private SearchUtil sUtil;
    
    
    public void setTableModel(TableModel model){
        if(model!=null){
            tblResult.setModel(model);
        }
    }
    
    private class GerEvents implements ActionListener {

        private JFrame frame;
        
        public GerEvents(JFrame frame){
            this.frame = frame;
        }
        
        @Override
        public void actionPerformed(ActionEvent e) {
            
            if(e.getSource() == btnCancel){
                frame.dispose();
            }
            else if(e.getSource() == btnOK){
                int sr = tblResult.getSelectedRow();
                if(sr > -1){
                    int sl = ((DefaultTableModel)tblResult.getModel()).findColumn(sUtil.getResultField());
                    sUtil.setValue(tblResult.getModel().getValueAt(sr, sl));
                    sUtil.getTxtField().setText((String)tblResult.getModel().getValueAt(sr, sl));
                    frame.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Selecione um registro!", "Grid", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else if(e.getSource() == btnSearch){
                
            }
            
        }
        
    }

}
