/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cmm.jft_ui.masterdata;

import com.cmm.jft.financial.Currency;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;

import com.cmm.jft_ui.ObjectForms;
import com.cmm.jft_ui.forms.AbstractForm;
import com.cmm.jft_ui.forms.Events;
import com.cmm.jft_ui.forms.FormsFactory;

/**
 *
 * @author Cristiano M Martins
 */
public class CurrencyForm extends AbstractForm {

    /**
     * Creates new form CurrencyForm
     */
    public CurrencyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        txtCurrencyID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCurrencyID1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblSign = new javax.swing.JLabel();
        btnQuotes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("CurrencyID");

        btnCancel.setText("Cancel");

        btnOK.setText("OK");

        txtCurrencyID.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtCurrencyID.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel2.setText("Description");

        txtCurrencyID1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtCurrencyID1.setMargin(new java.awt.Insets(1, 2, 1, 2));

        jLabel3.setText("Sign");

        lblSign.setText("$");

        btnQuotes.setText("Quotes");

        jLabel4.setText("Unit");

        txtUnit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtUnit.setMargin(new java.awt.Insets(1, 2, 1, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuotes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCurrencyID1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSign)
                                    .addComponent(txtCurrencyID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 154, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCurrencyID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrencyID1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnQuotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnQuotes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSign;
    private javax.swing.JTextField txtCurrencyID;
    private javax.swing.JTextField txtCurrencyID1;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
    
    private Currency data;
    
    @Override
    public void setData(Object data) {
        this.data = (Currency) data;
    }

    @Override
    public void addListeners() {
        btnCancel.addActionListener(new GerEvents(this));
        btnOK.addActionListener(new GerEvents(this));
        btnQuotes.addActionListener(new GerEvents(this));
    }

    @Override
    public void loadData() {
        
	if(data == null) {
	    btnQuotes.setEnabled(false);
	}else {
	    
	}
	
    }

    @Override
    public void close() {
        save();
    }

    @Override
    public void save() {
        
    }

    @Override
    public void remove() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    private class GerEvents extends Events{
		
	/**
	 * @param frame
	 */
	public GerEvents(AbstractForm frame) {
	    super(frame);
	}

	/* (non-Javadoc)
	 * @see java.awt.event.ActionListener#actionPerformed(java.awt.event.ActionEvent)
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
	    if(e.getSource() == btnCancel) {
		close();
	    } else if(e.getSource() == btnOK) {
		
	    } else if(e.getSource() == btnQuotes) {
		FormsFactory.openForm(ObjectForms.CURRENCY_QUOTES, data);
	    }
	    
	}

	/* (non-Javadoc)
	 * @see java.awt.event.WindowListener#windowClosed(java.awt.event.WindowEvent)
	 */
	@Override
	public void windowClosed(WindowEvent e) {
	    close();
	}
	
    }
    
}
